export const TEMARIOS = {
  "1ro de Bachillerato": [
    { "semana": 1, "tema": "Inducción y ciudadanía digital (identidad y huella digital)", "objetivos_aprendizaje": "Reconocer normas de convivencia digital y construir su perfil de ciudadanía digital." },
    { "semana": 2, "tema": "Seguridad básica y netiqueta", "objetivos_aprendizaje": "Aplicar prácticas seguras de contraseñas y netiqueta en entornos académicos." },
    { "semana": 3, "tema": "HTML: Introducción y estructura básica", "objetivos_aprendizaje": "Comprender la estructura de un documento HTML (<!DOCTYPE>, <html>, <head>, <body>)." },
    { "semana": 4, "tema": "HTML: Encabezados, párrafos y enlaces", "objetivos_aprendizaje": "Usar etiquetas de texto y enlaces internos/externos." },
    { "semana": 5, "tema": "HTML: Imágenes y listas", "objetivos_aprendizaje": "Insertar imágenes con atributos adecuados y crear listas ordenadas/no ordenadas." },
    { "semana": 6, "tema": "HTML: Tablas básicas", "objetivos_aprendizaje": "Crear tablas para organizar información simple." },
    { "semana": 7, "tema": "Word: Formato y estilos", "objetivos_aprendizaje": "Aplicar estilos y formato coherente en documentos." },
    { "semana": 8, "tema": "Word: Tablas e imágenes", "objetivos_aprendizaje": "Insertar y dar formato a tablas e imágenes en un informe." },
    { "semana": 9, "tema": "Word: Referencias básicas", "objetivos_aprendizaje": "Gestionar saltos de sección, numeración y citas básicas." },
    { "semana": 10, "tema": "Presentaciones efectivas: Principios de diseño", "objetivos_aprendizaje": "Aplicar principios de diseño (contraste, alineación, repetición, proximidad)." },
    { "semana": 11, "tema": "Presentaciones: Storytelling y visualización", "objetivos_aprendizaje": "Estructurar mensajes con narrativa y visuales adecuados." },
    { "semana": 12, "tema": "Presentaciones: Ensayo y feedback", "objetivos_aprendizaje": "Mejorar la presentación con retroalimentación entre pares." },
    { "semana": 13, "tema": "Excel: Introducción y tipos de datos", "objetivos_aprendizaje": "Reconocer interfaz, tipos de datos y referencias relativas/absolutas." },
    { "semana": 14, "tema": "Excel: Fórmulas y funciones básicas", "objetivos_aprendizaje": "Usar SUMA, PROMEDIO, MAX, MIN, CONTAR." },
    { "semana": 15, "tema": "Excel: Formato condicional y ordenamiento", "objetivos_aprendizaje": "Aplicar formato condicional y ordenar/filtrar datos." },
    { "semana": 16, "tema": "Proyecto 1: Mini sitio HTML + ciudadanía digital", "objetivos_aprendizaje": "Integrar HTML básico y mensajes de uso responsable de Internet." },
    { "semana": 17, "tema": "IoT: Conceptos y casos de uso", "objetivos_aprendizaje": "Comprender qué es IoT, sensores/actuadores y ejemplos cotidianos." },
    { "semana": 18, "tema": "IoT: Datos y consideraciones básicas", "objetivos_aprendizaje": "Identificar flujos de datos y considerar privacidad y seguridad." },
    { "semana": 19, "tema": "Ética digital: Propiedad intelectual y plagio", "objetivos_aprendizaje": "Citar y respetar licencias; evitar plagio académico." },
    { "semana": 20, "tema": "Ética digital: Bienestar y tiempo en pantalla", "objetivos_aprendizaje": "Gestionar bienestar digital y uso equilibrado de pantallas." },
    { "semana": 21, "tema": "HTML: Formularios básicos", "objetivos_aprendizaje": "Crear formularios con input, label, select y textarea." },
    { "semana": 22, "tema": "HTML: Estructura semántica", "objetivos_aprendizaje": "Emplear etiquetas semánticas (header, nav, main, section, footer)." },
    { "semana": 23, "tema": "Word: Tablas de contenido y referencias cruzadas", "objetivos_aprendizaje": "Generar tabla de contenido automática y referencias cruzadas." },
    { "semana": 24, "tema": "Word: Control de cambios y coautoría", "objetivos_aprendizaje": "Colaborar usando control de cambios y comentarios." },
    { "semana": 25, "tema": "Excel: Gráficos básicos", "objetivos_aprendizaje": "Crear gráficos de columnas, líneas y sectores." },
    { "semana": 26, "tema": "Excel: Funciones condicionales (SI, CONTAR.SI, SUMAR.SI)", "objetivos_aprendizaje": "Aplicar funciones condicionales a problemas simples." },
    { "semana": 27, "tema": "Presentaciones: Pitch de proyecto", "objetivos_aprendizaje": "Sintetizar y presentar hallazgos/proyectos." },
    { "semana": 28, "tema": "Proyecto 2: Integración (Word + Excel + HTML)", "objetivos_aprendizaje": "Integrar productos en un pequeño portafolio digital." },
    { "semana": 29, "tema": "Proyecto 2: Revisión y retroalimentación", "objetivos_aprendizaje": "Aplicar feedback para mejorar el portafolio." },
    { "semana": 30, "tema": "Cierre y evaluación final", "objetivos_aprendizaje": "Reflexionar sobre logros y evidenciar competencias." }
  ],
  "2do de Bachillerato": [
    { "semana": 1, "tema": "Ciudadanía digital avanzada: identidad y privacidad", "objetivos_aprendizaje": "Analizar riesgos y configurar privacidad en servicios frecuentes." },
    { "semana": 2, "tema": "Ciberseguridad básica: phishing y 2FA", "objetivos_aprendizaje": "Identificar señales de phishing y activar 2FA." },
    { "semana": 3, "tema": "HTML: Semántica y accesibilidad", "objetivos_aprendizaje": "Usar etiquetas semánticas y atributos de accesibilidad (alt, roles)." },
    { "semana": 4, "tema": "HTML: Estructuras multisección", "objetivos_aprendizaje": "Organizar contenido en secciones coherentes y navegables." },
    { "semana": 5, "tema": "HTML: Formularios accesibles", "objetivos_aprendizaje": "Mejorar formularios con labels y mensajes de ayuda." },
    { "semana": 6, "tema": "HTML: Buenas prácticas y SEO básico", "objetivos_aprendizaje": "Aplicar títulos, metaetiquetas y estructura para comprensión." },
    { "semana": 7, "tema": "Excel: Tablas, nombres y validación", "objetivos_aprendizaje": "Convertir rangos en tablas, usar nombres y validar entradas." },
    { "semana": 8, "tema": "Excel: Funciones condicionales avanzadas", "objetivos_aprendizaje": "Emplear SI anidado, SI.CONJUNTO y funciones lógicas." },
    { "semana": 9, "tema": "Excel: Texto y fecha", "objetivos_aprendizaje": "Transformar textos y fechas (CONCAT, UNIRCADENAS, IZQUIERDA, EXTRAE, AÑO/MES/DÍA)." },
    { "semana": 10, "tema": "Excel: Búsqueda y referencia", "objetivos_aprendizaje": "Aplicar INDICE+COINCIDIR, BUSCARV o BUSCARX." },
    { "semana": 11, "tema": "Word: Plantillas y estilos avanzados", "objetivos_aprendizaje": "Crear plantillas reutilizables con estilos consistentes." },
    { "semana": 12, "tema": "Word: Combinación de correspondencia y formularios", "objetivos_aprendizaje": "Automatizar documentos con combinación y controles de contenido." },
    { "semana": 13, "tema": "Presentaciones: Visualización de datos", "objetivos_aprendizaje": "Integrar gráficos y tablas legibles." },
    { "semana": 14, "tema": "Presentaciones: Guion y entrega", "objetivos_aprendizaje": "Estructurar guion persuasivo y practicar entrega." },
    { "semana": 15, "tema": "Presentaciones: Diseño avanzado", "objetivos_aprendizaje": "Aplicar tipografía, color y composición avanzadas." },
    { "semana": 16, "tema": "Proyecto 1: Sitio HTML informativo accesible", "objetivos_aprendizaje": "Integrar semántica, formularios y accesibilidad básica." },
    { "semana": 17, "tema": "IoT: Arquitectura y componentes", "objetivos_aprendizaje": "Describir sensores, conectividad y plataforma." },
    { "semana": 18, "tema": "IoT: Protocolos y casos (nivel introductorio)", "objetivos_aprendizaje": "Reconocer flujos de datos y protocolos comunes (visión general)." },
    { "semana": 19, "tema": "IoT: Datos, privacidad y seguridad", "objetivos_aprendizaje": "Valorar implicaciones éticas y de protección de datos." },
    { "semana": 20, "tema": "Excel: Tablas dinámicas I", "objetivos_aprendizaje": "Crear tablas dinámicas y segmentaciones." },
    { "semana": 21, "tema": "Excel: Tablas dinámicas II (campos calculados)", "objetivos_aprendizaje": "Agregar métricas personalizadas." },
    { "semana": 22, "tema": "Excel: Gráficos combinados y segmentación", "objetivos_aprendizaje": "Comunicar tendencias con gráficos apropiados." },
    { "semana": 23, "tema": "Ética digital: Desinformación y sesgos", "objetivos_aprendizaje": "Detectar desinformación y reflexionar sobre sesgos algorítmicos." },
    { "semana": 24, "tema": "Ética digital: IA responsable (nivel básico)", "objetivos_aprendizaje": "Usar IA de forma responsable (privacidad, autoría, citas)." },
    { "semana": 25, "tema": "Proyecto 2 (Excel): Diseño de dashboard I", "objetivos_aprendizaje": "Planificar un dashboard con KPIs relevantes." },
    { "semana": 26, "tema": "Proyecto 2 (Excel): Construcción II", "objetivos_aprendizaje": "Construir tablas dinámicas y gráficos vinculados." },
    { "semana": 27, "tema": "Proyecto 2 (Excel): Diseño y narrativa III", "objetivos_aprendizaje": "Afinar diseño y narrativa de insights." },
    { "semana": 28, "tema": "Proyecto 2 (Excel): Cierre y documentación", "objetivos_aprendizaje": "Documentar uso y limitaciones del dashboard." },
    { "semana": 29, "tema": "Portafolio digital", "objetivos_aprendizaje": "Compilar evidencias de aprendizaje del curso." },
    { "semana": 30, "tema": "Cierre y evaluación final", "objetivos_aprendizaje": "Evidenciar competencias y reflexionar sobre aprendizajes." }
  ],
  "3ro de Bachillerato": [
    { "semana": 1, "tema": "Diagnóstico y buenas prácticas", "objetivos_aprendizaje": "Identificar nivel inicial y acordar estándares de archivo y formato." },
    { "semana": 2, "tema": "Fundamentos: interfaz y referencias", "objetivos_aprendizaje": "Dominar referencias relativas, absolutas y mixtas." },
    { "semana": 3, "tema": "Funciones básicas I", "objetivos_aprendizaje": "Aplicar SUMA, PROMEDIO, MAX, MIN, CONTAR, CONTARA." },
    { "semana": 4, "tema": "Funciones básicas II", "objetivos_aprendizaje": "Usar REDONDEAR, ABS, POTENCIA, RANGLÓGICO básico." },
    { "semana": 5, "tema": "Funciones condicionales", "objetivos_aprendizaje": "Emplear SI, SI.CONJUNTO y operadores lógicos." },
    { "semana": 6, "tema": "Funciones de texto I", "objetivos_aprendizaje": "Transformar textos con IZQUIERDA, DERECHA, EXTRAE, LARGO." },
    { "semana": 7, "tema": "Funciones de texto II", "objetivos_aprendizaje": "Combinar textos con CONCAT, UNIRCADENAS y LIMPIAR/ESPACIOS." },
    { "semana": 8, "tema": "Funciones de fecha y hora", "objetivos_aprendizaje": "Usar HOY, AHORA, FECHA, AÑO/MES/DÍA, DIAS, DIAS.LAB." },
    { "semana": 9, "tema": "Búsqueda y referencia I", "objetivos_aprendizaje": "Emplear BUSCARV/BUSCARH con criterios exactos y aproximados." },
    { "semana": 10, "tema": "Búsqueda y referencia II", "objetivos_aprendizaje": "Aplicar INDICE+COINCIDIR y BUSCARX (si disponible)." },
    { "semana": 11, "tema": "Tablas y validación de datos", "objetivos_aprendizaje": "Crear tablas estructuradas, nombres y validaciones dependientes." },
    { "semana": 12, "tema": "Formato condicional avanzado", "objetivos_aprendizaje": "Reglas con fórmulas y barras/escala de color." },
    { "semana": 13, "tema": "Gráficos I (básicos)", "objetivos_aprendizaje": "Crear gráficos de columnas, líneas y sectores correctamente etiquetados." },
    { "semana": 14, "tema": "Gráficos II (combinados y secundarios)", "objetivos_aprendizaje": "Diseñar gráficos combinados y usar ejes secundarios." },
    { "semana": 15, "tema": "Gráficos III (minigráficos, diseño)", "objetivos_aprendizaje": "Usar minigráficos y aplicar mejores prácticas de diseño." },
    { "semana": 16, "tema": "Tablas dinámicas I", "objetivos_aprendizaje": "Crear tablas dinámicas y segmentaciones básicas." },
    { "semana": 17, "tema": "Tablas dinámicas II (campos calculados)", "objetivos_aprendizaje": "Agregar métricas personalizadas." },
    { "semana": 18, "tema": "Análisis hipotético I", "objetivos_aprendizaje": "Usar Buscar objetivo y Escenarios." },
    { "semana": 19, "tema": "Análisis hipotético II (Tablas de datos)", "objetivos_aprendizaje": "Construir tablas de datos a 1 y 2 variables." },
    { "semana": 20, "tema": "Optimización con Solver (si disponible)", "objetivos_aprendizaje": "Plantear y resolver problemas simples de optimización." },
    { "semana": 21, "tema": "Modelos financieros básicos", "objetivos_aprendizaje": "Calcular intereses, VAN y TIR (introducción)." },
    { "semana": 22, "tema": "Power Query (si disponible) o limpieza manual", "objetivos_aprendizaje": "Importar/transformar datos o aplicar técnicas de limpieza." },
    { "semana": 23, "tema": "Automatización básica: Grabadora de macros (opcional)", "objetivos_aprendizaje": "Comprender la grabación de pasos repetitivos y buenas prácticas." },
    { "semana": 24, "tema": "Proyecto integrador I: Definición", "objetivos_aprendizaje": "Definir problema, KPIs, fuentes y cronograma." },
    { "semana": 25, "tema": "Proyecto integrador II: Construcción", "objetivos_aprendizaje": "Construir modelo base, tablas dinámicas y gráficos." },
    { "semana": 26, "tema": "Proyecto integrador III: Controles e interactividad", "objetivos_aprendizaje": "Agregar segmentaciones, validaciones y diseño." },
    { "semana": 27, "tema": "Proyecto integrador IV: Pruebas y QA", "objetivos_aprendizaje": "Probar, corregir errores y documentar supuestos." },
    { "semana": 28, "tema": "Documentación y guía de usuario", "objetivos_aprendizaje": "Redactar guía clara para uso y mantenimiento." },
    { "semana": 29, "tema": "Presentación del proyecto", "objetivos_aprendizaje": "Comunicar hallazgos y recibir feedback." },
    { "semana": 30, "tema": "Evaluación final y cierre", "objetivos_aprendizaje": "Evidenciar dominio de Excel y reflexionar sobre aprendizaje." }
  ]
}